version: "3.9"

services:
  backend:
    build:
      context: ./server
    container_name: grant-mesra-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
      - "${HTTPS_PORT:-4443}:${HTTPS_PORT:-4443}"
    volumes:
      - logs:/app/logs
      - ./server/certs:/app/certs:ro
      - ./server/.env:/app/.env:ro
    networks:
      - r3tro_retro-network

volumes:
  db_data:
  logs:

networks:
  r3tro_retro-network:
    external: true
