version: "3.9"

services:
  backend:
    build:
      context: ./server
    container_name: grant-mesra-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"
      - "${HTTPS_PORT:-4443}:${HTTPS_PORT:-4443}"
    volumes:
      - logs:/app/logs
      - ./server/certs:/app/certs:ro
      - ./server/.env:/app/.env:ro

volumes:
  db_data:
  logs:
